### ISSUE TITLE
Why CharBuffer provided by MPI slower than original char[]?

### ISSUE THREAD

**Issue by cantbesure** [gpichot/mpi-zmq-benchmarks#1]
I tried CharBuffer provided by Java and MPI, and char[]. The MPI one is the slowest. 
Is there any settings or parameters need to be done before test?
Thx!

**Comment by gpichot** [comment]
Do you mean that you run the tests with Java only, and the MPI benchmark with both `char[]` and `CharBuffer` ?

**Comment by cantbesure** [comment]
```java
            CharBuffer buffer = MPI.newCharBuffer(WIDTH);
            // CharBuffer buffer = CharBuffer.allocate(WIDTH);
            // char [] buffer=new char[WIDTH];
```
I tried these three data structures of Java.
The best performance is ``` char [] buffer=new char[WIDTH];```
It's kind of strange bcz the readme.java.txt of OpenMPI says ```MPI.newCharBuffer(WIDTH);``` should be better.

Actually I'm running some benchmarks to compare the performance of  Java and C MPI interface.

**Comment by gpichot** [comment]
Quote from: https://github.com/open-mpi/ompi-java-test
> Direct buffers aren't a replacement for arrays, because they have
> higher allocation and deallocation costs than arrays. In some
> cases arrays will be a better choice.

Quote from https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html 
> A direct byte buffer may be created by invoking the allocateDirect factory method of this class. The buffers returned by this method typically have somewhat higher allocation and deallocation costs than non-direct buffers. The contents of direct buffers may reside outside of the normal garbage-collected heap, and so their impact upon the memory footprint of an application might not be obvious. It is therefore recommended that direct buffers be allocated primarily for large, long-lived buffers that are subject to the underlying system's native I/O operations. In general it is best to allocate direct buffers only when they yield a measureable gain in program performance.

Have you tried with bigger messages?

When I benchmarked these something like two years ago, the C interface was faster than the Java interface, which seems reasonable given the fact that the Java interface is just a binding of the C interface.

**Comment by cantbesure** [comment]
That is the point, bcz when I profiled it, the allocate function take a lot of time especailly in the first iterations. Yes! The Java version is just a binding of the C interface.
It is just the beginning of our project for some small tests. I will try some big messages after.

So I think it will be a little bit better to use ```java array``` in this situation. 

Thx for your work and quote!
